import = ["~/.config/alacritty/rose-pine-moon.toml"]

[window]
opacity = 0.95

[colors]
transparent_background_colors = true

[font]
normal.family = "JetBrainsMonoNL"
normal.style = "SemiBold"
bold.family = "JetBrainsMonoNL"
bold.style = "ExtraBold"
italic.family = "JetBrainsMonoNL"
italic.style = "SemiBold Italic"
bold_italic.family = "JetBrainsMonoNL"
bold_italic.style = "ExtraBold Italic"
size = 11.1

[scrolling]
history = 100000

[selection]
save_to_clipboard = true
