
[window]
opacity = 0.95

[colors]
transparent_background_colors = true

[font]
normal.family = "JetBrains Mono Nerd Font"
normal.style = "Medium"
bold.family = "JetBrains Mono Nerd Font"
bold.style = "Bold"
italic.family = "JetBrains Mono Nerd Font"
italic.style = "MediumItalic"
bold_italic.family = "JetBrains Mono Nerd Font"
bold_italic.style = "BoldItalic"
size = 11.25

[keyboard]
bindings = [{ key = ";", mods = "Control", action = "IncreaseFontSize" }]

[scrolling]
history = 100000

[terminal]
osc52 = "CopyPaste"

[selection]
save_to_clipboard = true

[general]
import = ["~/.config/alacritty/rose-pine-moon.toml"]
