import = ["~/.config/alacritty/rose-pine-moon.toml"]

[window]
opacity = 0.95

[colors]
transparent_background_colors = true

[font]
normal.family = "JetBrainsMonoNL"
bold.family = "JetBrainsMonoNL"
italic.family = "JetBrainsMonoNL"
bold_italic.family = "JetBrainsMonoNL"
size = 11

[scrolling]
history = 100000

[selection]
save_to_clipboard = true
